---
title: 'Make Your Work : fasteR'
author: 'Hyeongchan Bae'
date: 'April 2022'
output: 
 pdf_document:
   latex_engine: xelatex
mainfont: NanumGothic   
fontsize: 12pt
linestretch: 1.5
---

# 1. Setting

## 1-1. Download

**R** 프로그래밍 언어. 제일 먼저 설치

* https://cran.r-project.org/bin/windows/base

**RStudio** R을 활용하기 위한 통합개발환경(IDE, Integrated Development Environment)

* 달리 말하면 RStudio 외에도 다양한 프로그램에서 R을 사용할 수 있음. 여러 언어를 사용하는 개발자는 VS Code 같은 단일 IDE를 활용하기도. 

* https://www.rstudio.com/products/rstudio/download

**Rtools** 패키지를 설치하다 보면 필요한 경우(Compile)가 더러 있음

* https://cran.r-project.org/bin/windows/Rtools

**Chrome Browser** Selenium 파트에서 사용할 예정

* https://www.google.com/intl/ko_kr/chrome

**Extra Files** 인턴의 깃허브 페이지. 강의 노트, 작성 코드 등 추가적인 파일을 업로드 해둠

* https://github.com/Rlearnchan/fasteR

## 1-2. Something to know

### 1) 우리는 세상이란 무대에서 모두 다 같은 아마추어야

익숙지 않고, 오래 걸리는 게 당연해요.

모든 과정을 R로 수행할 필요는 없으니, 잘 안 되면 데이터를 엑셀, STATA 등으로 옮겨 처리해오셔도 좋습니다. 저도 처음엔 그렇게 배웠답니다.

### 2) RStudio를 사용하면 만나게 될 파일(확장자)**

**.R** 작성한 코드

* 좌상단 Script에서 코드 작성 \rightarrow\ 필요한 부분 실행 \rightarrow\ 좌하단 Console 창에서 실행 결과를 확인하는 게 일반적이라, 작업 첫 파트를 저장한 것이라 볼 수 있음.

* 코드를 적은 메모장쯤 되니, **비슷한 환경**이라면 타인에게 받은 코드를 실행하기만 해도 같은 결과를 시현함.

여기서 **비슷한 환경**은 다음 파일들로 구축, 전달할 수 있음.

**.Rdata** 작업공간 이미지

* 우상단 Environment에 기록된, 작업하며 생성된 객체, 함수, 기타 데이터들의 총체.

* 임시로 만든, 코드 실행과 무관환 object 들도 저장. 

**.Rhistory** 작업 기록

* RStudio를 종료했다가, 다시 실행하면 이전 작업 상태가 비교적 온전히 남아있는데, 이를 위한 파일이라 하겠음.

강의에서는 잘 다루지 않겠으나, 이런 것도 있음.

**.Rmd** 마크다운 파일

* html, pdf, word 등을 만들기 위해 Markdown 문법으로 작성한, 코드 친구쯤 되는 녀석.

* 본 문서도 마크다운 \rightarrow\ Tex \rightarrow\ PDF 식으로 작성. 소위 'R로 논문 쓴다' 할 때 등장.

### 3) 한글에 유독 취약한 R

